#!/bin/bash

set -euo pipefail
IFS=$'\n\t'
# Strict mode ^

# Functions go here :

downloadContent() {
  echo "downloadContent function executed"
  echo "Thread URL is: " $threadURL
  echo "Board name is: " $boardName
  echo "Thread number is: " $threadNumber
  # wget -nd -r --level=1 -e robots=off -A jpg,jpeg,png,webp,gif,webm,tmp,html -H --wait 1 $threadURL

  mkdir -p $boardName/$threadNumber
  wget -P $boardName/$threadNumber -nd -r -p -e robots=off -D i.4cdn.org -A jpg,jpeg,png,webp,gif,webm,tmp,html,mp4,mp3,m4a -H $threadURL/ -q --show-progress


  #Cleanup the preview files, this used to be the "keepOrDelete" functionality, but this has been removed as of version 2.1+
  find -type f -name '*s.*' -delete
}

downloadThread() {
  echo "downloadThread function executed"
  echo "Thread URL is: " $threadURL
  echo "Board name is: " $boardName
  echo "Thread number is: " $threadNumber

  # Notes to self :
  # What some bro on 4chan gave to me to answer this issue :
  # wget -r -H -D i.4cdn.org,boards.4channel.org -I "$boardName",thread -p -P . -A html,jpg,jpeg,gif,png,webm https://boards.4channel.org/$boardName/thread/<thread#> -e robots=off --wait 1 $threadURL
  # My modified version can be found below
  # wget -r -H --page-requisites -D i.4cdn.org/$boardName , boards.4channel.org/$boardName, boards.4chan.org/$boardName -I "$boardName",thread -p -P --convert-links -A html,jpg,jpeg,gif,png,webm https://boards.4channel.org/$boardName/thread/$threadNumber -e robots=off --wait 1 $threadURL
  #
  # The part that does not work is the -D flag where it tries to just allow itself to download from those URLs. It has to be fully recursive or limit the recursion for now.

  # Notes to self ^^

  wget -m -l 1 -np -p -e robots=off -w 1 -k $threadURL -q --show-progress

  #Cleanup the preview files, this used to be the "keepOrDelete" functionality, but this has been removed as of version 2.1+
  find -type f -name '*s.*' -delete

}

downloadEverything() {
  echo "downloadEverything function executed"
  echo "Thread URL is: " $threadURL
  echo "Board name is: " $boardName
  echo "Thread number is: " $threadNumber

  wget -m -l 1 -nd -np -P $boardName/$threadNumber -e robots=off -k -w 1 $threadURL -q --show-progress
  wget -P $boardName/$threadNumber -nd -np -r -p -e robots=off -D i.4cdn.org -A jpg,jpeg,png,webp,gif,webm,tmp,html,mp4,mp3,m4a -H $threadURL/ -q --show-progress

  #Cleanup the preview files, this used to be the "keepOrDelete" functionality, but this has been removed as of version 2.1+
  find -type f -name '*s.*' -delete
}


#Other functions not related to thread downloading :

makeDirectory(){
  echo "What would you like the name of the directory where contents are downloaded to to be ? "
  read -p "" dirName
  echo "Making directory :" $dirName
  mkdir $dirName
  echo "cd'ing to :" $dirName
  cd $dirName
}


# STARTS HERE, aka querying the user, all of the special functions go above
# $(tput setaf 3) is used for making the text green.
echo "					Cipher's 4chan thread download tool"
printf "
  / // / ____/ /___ _      ______
 / // /_/ __  / __ \\ | /| / / __ \\
/__  __/ /_/ / /_/ / |/ |/ / / / /
  /_/  \\____/\\____/|__/|__/_/ /_/
" 

makeDirectory
echo "Enter the URL of the thread that you want to download: " 
read -p "" threadURL
echo "$threadURL"  

urlLength=${#threadURL}

# https://boards.4channel.org/wsg/thread/4483299
# Example thread ^^^

# Make a copy of threadURL (original value inputted by the user) into threadURLStripped to modify
threadURLStripped=$threadURL
echo $threadURLStripped

threadURLStripped="${threadURLStripped#https://boards.4channel.org}"
threadURLStripped="${threadURLStripped#https://boards.4chan.org}"
#echo "$threadURLStripped"
threadURLStripped=${threadURLStripped//thread/}
#echo "$threadURLStripped"
threadURLStripped=${threadURLStripped///}
#echo "$threadURLStripped"
threadURLStripped=${threadURLStripped//[0-9]/}
#echo "$threadURLStripped"

boardName=$threadURLStripped

threadNumStripped=$threadURL
threadNumStripped="${threadNumStripped#https://boards.4channel.org}"
#echo "$threadURLStripped"
threadNumStripped=${threadNumStripped//thread/}
#echo "$threadNumStripped"
threadNumStripped=${threadNumStripped///}
#echo "$threadNumStripped"
threadNumStripped=${threadNumStripped//[!0-9]/}
#echo "$threadNumStripped"

threadNumber=$threadNumStripped

printf "Which of the following choices do you want? \n 1) Download just the content from the thread (images and videos). \n 2) Download the entire thread and all of the stuff required to display it. \n 3) 2 and 1 combined, it downloads all of the content and a visible version of the thread!\n"
read -p "Answer choice, here (Number associated with option): " userChoice
echo $userChoice
read -p "Are you ready to proceed? (Enter y/n): " proceed
if [ $proceed == y ] || [ $proceed == Y ]; then
  echo "Commencing!"
fi

# use case statement to determine which choice the user has chosen
case $userChoice in
1)
  downloadContent
  ;;
2)
  downloadThread
  ;;
3)
  downloadEverything
  ;;
*)
  echo "Invalid choice"
  ;;
esac

# Wow, you're reading this! That must mean that you're reading over the software you use! Yay!
