#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

# Functions

downloadContent() {
  echo "downloadContent function executed"
  echo "Thread URL is: $threadURL"
  echo "Board name is: $boardName"
  echo "Thread number is: $threadNumber"

  # Use wget to download only full-size images and videos, avoiding the 's' versions.
  wget -r -np -nH -nd -e robots=off -A "jpg,jpeg,png,webp,gif,webm,mp4,mp3,m4a" -R "*s.jpg,*s.jpeg,*s.png,*s.webp" -H "$threadURL" -q --show-progress
}

downloadThread() {
  echo "downloadThread function executed"
  echo "Thread URL is: $threadURL"
  echo "Board name is: $boardName"
  echo "Thread number is: $threadNumber"

  wget -m -l 1 -np -nd -p -e robots=off -w 1 -k "$threadURL" -q --show-progress
}

downloadEverything() {
  echo "downloadEverything function executed"
  echo "Thread URL is: $threadURL"
  echo "Board name is: $boardName"
  echo "Thread number is: $threadNumber"

  wget -m -l 1 -nd -np -e robots=off -k -w 1 "$threadURL" -q --show-progress
  wget -r -np -nH -nd -e robots=off -A "jpg,jpeg,png,webp,gif,webm,mp4,mp3,m4a" -R "*s.jpg,*s.jpeg,*s.png,*s.webp" -H "$threadURL" -q --show-progress
}

# Main execution
echo "                                  Cipher's 4chan thread download tool"
printf "
  / // / ____/ /___ _      ______
 / // /_/ __  / __ \\ | /| / / __ \\
/__  __/ /_/ / /_/ / |/ |/ / / / /
  /_/  \\____/\\____/|__/|__/_/ /_/
" | lolcat

echo "As a note you should also have cd'd into the directory where you want all of these contents to download to" | lolcat
echo "Enter the URL of the thread that you want to download: " | lolcat
read -p "" threadURL

# Extracting board name and thread number from URL
threadURLStripped="${threadURL#https://boards.4channel.org}"
threadURLStripped="${threadURLStripped#https://boards.4chan.org}"
threadURLStripped=${threadURLStripped//thread/}
threadURLStripped=${threadURLStripped///}
boardName=${threadURLStripped//[0-9]/}

threadNumStripped=${threadURL#https://boards.4channel.org}
threadNumStripped=${threadNumStripped//thread/}
threadNumStripped=${threadNumStripped///}
threadNumber=${threadNumStripped//[!0-9]/}

# User choice
printf "Which of the following choices do you want? \n 1) Download just the content from the thread (images and videos). \n 2) Download a copy of the thread (does not include the images/videos as their own files) . \n 3) 2 and 1 combined, it downloads all of the content and a visible version of the thread!\n"
read -p "Answer choice, here (Number associated with option): " userChoice
read -p "Are you ready to proceed? (Enter y/n): " proceed
if [ "$proceed" != "y" ] && [ "$proceed" != "Y" ]; then
  echo "Operation aborted."
  exit 1
fi

# Case statement for user choice
case $userChoice in
1)
  downloadContent
  ;;
2)
  downloadThread
  ;;
3)
  downloadEverything
  ;;
*)
  echo "Invalid choice"
  ;;
esac
